export const ITEMS_PER_PAGE_VIEW_ALL = 20
export const TITLE_SECTIONS = {
  TRENDING: 'TRENDING NOW',
  POPULAR: 'POPULAR THIS SEASON',
  UPCOMING: 'UPCOMING NEXT SEASON',
  ALL_TIME: 'ALL TIME POPULAR',
  TOP_100: 'TOP 100 ANIME',
}
